language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-10
            - gnuplot
      services:
        - xvfb
      env:
         - MATRIX_EVAL="CXX=g++-10"
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - g++-10
            - clang-11
            - gnuplot
      services:
        - xvfb
      env:
         - MATRIX_EVAL="CXX=clang++-11"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - ${CXX} --version
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./src/gpxx-demo1 < <(sleep 1; echo)
  - ./src/gpxx-demo2 < <(sleep 1; echo)
  - ./src/gpxx-chaiscript ../src/demo1.chai < <(sleep 1; echo)
  - ./src/gpxx-chaiscript ../src/demo2.chai < <(sleep 1; echo)
